In [50]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Introduction to tensors

### creating tensors



In [51]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [52]:
scalar.ndim

0

In [53]:
# vector
vector =  torch.tensor([7, 7])
vector

tensor([7, 7])

In [54]:
vector.ndim

1

In [55]:
vector.shape

torch.Size([2])

In [56]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [57]:
MATRIX.ndim

2

In [58]:
MATRIX[1]

tensor([ 9, 10])

In [59]:
MATRIX.shape

torch.Size([2, 2])

In [60]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [61]:
TENSOR.ndim

3

In [62]:
TENSOR.shape

torch.Size([1, 3, 3])

In [63]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### random tensor

why randon tensor


random tensor are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


'start with random numbers -> look at data ->update random number -> look at data -> update random number '

In [64]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9014, 0.2581, 0.9343, 0.8464],
        [0.1860, 0.8239, 0.9381, 0.0652],
        [0.2375, 0.6242, 0.7508, 0.6899]])

In [65]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (r, g, b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [66]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [67]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
ones.dtype

torch.float32

In [69]:
random_tensor.dtype

torch.float32

### creating a range of tensor and tensor-like

In [70]:
# use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
# creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

**note** tensor datatypes are one of the three big errors you'll run into with PyTorch & deep learning:
1. Tensor is not the right datatype
2. Tensor is not the right shape
3. Tensor is not the right device

In [72]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
              dtype=None, # what datatype is the tensor(e.g. float32 or float16)
              device=None, # what device is your on
              requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [73]:
float_32_tensor.dtype

torch.float32

In [74]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [75]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [76]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [77]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes )

1. Tensor is not the right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor is not the right shape - to get shape from tensor, can use `tensor.shape`
3. Tensor is not the right device - to get device from tensor, can use `tensor.device`

In [78]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0029, 0.0725, 0.8218, 0.1553],
        [0.7188, 0.9454, 0.5328, 0.9882],
        [0.5804, 0.5921, 0.8423, 0.5666]])

In [79]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [80]:
some_tensor.size()

torch.Size([3, 4])

In [81]:
# find out details about some tensor
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of  tensor: {some_tensor.shape}")
print(f"device of tensor is on: {some_tensor.device}")

tensor([[0.0029, 0.0725, 0.8218, 0.1553],
        [0.7188, 0.9454, 0.5328, 0.9882],
        [0.5804, 0.5921, 0.8423, 0.5666]])
datatype of tensor: torch.float32
shape of  tensor: torch.Size([3, 4])
device of tensor is on: cpu


##Tensor Manipulation
(Tensor operation includes)
  * Addition
  * Subtraction
  * Multiplication (element-wise)
  * Division
  * Matrix Multiplication


In [82]:
# create a tensor and add 10 to it
tensor=torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [83]:
# multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [84]:
tensor

tensor([1, 2, 3])

In [85]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

In [86]:
# try out PyTorch in-built torch.Function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [87]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication

two main way of perfoming multiplication in neural network and deep learning
* Element-wise multiplication
* Matrix  multiplication (dot product)
There are two main rules that perform matrix multiplication needs to satisfy :
1. The **inner dimension ** must match
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work

2. The resulting matrix has the spae of the **outer dimension **:
*'(2,3) @ (3,2)' -> (2,2)
* (3,2) @ (2,3) -> (3,3)


In [88]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [89]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [90]:
tensor

tensor([1, 2, 3])

In [91]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [92]:
%%time
value = 0
for i in range(len(tensor )):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.02 ms, sys: 2 µs, total: 1.02 ms
Wall time: 913 µs


In [93]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 32 µs, sys: 2 µs, total: 34 µs
Wall time: 36 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [94]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                           [5, 6],])

tensor_B = torch.tensor([[7, 10],
                         [8, 11 ],
                         [9, 12],])

# torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it’s an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T

In [ ]:
tensor_A.shape, tensor_B.shape

To Fix our tensor shape issue, we can manipulate the shape of one of our tensors using ***transposes***

A **transpose** switch the axes or dimensions  of the given tensor

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
#The matrix multiplication operation works when tensor_b is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A, tensor_B.T).shape

## finding the min max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x =  torch.arange(1, 100, 10)
x, x.dtype

In [ ]:
# find the min
torch.min(x), x.min()

In [ ]:
# find the max
torch.max(x), x.max()

In [ ]:
# find the mean - note: the torch.mean() function requires a tensor  of  float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# find the sum
torch.sum(x), x.sum()

## finding the positional min and max

In [ ]:
x

In [ ]:
# find the position in tensors that has the minimum value with argmin() -> return index position of targt tensor where the minimum value occurs
x.argmin()

In [ ]:
x[0]

In [ ]:
# find the position in tensors that has the maximum value with argmin()
x.argmax()

In [ ]:
x[9]

## reshaping, stacking, squeezing, and unsqueezing tensor

* reshaping - reshape an tensor to a defined shape
* View - Return  a view of an input tensor of certain shape but keep the same memory as the original  tensor
*Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - remove all `1` dimensions  from from a tensor
* unsqueeze - add a `1` a dimention to a target tensor
*permute - Return a view of the input with dimension permuted  (swapped) in certain way

In [99]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [100]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [101]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [102]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [103]:
# stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [108]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")

# remove extra dimensions from  x_reshaped

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [105]:
x_reshaped.shape

torch.Size([1, 9])

In [106]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [107]:
x_reshaped.squeeze().shape

torch.Size([9])